
ARGS:
 tab: 'test'
 GPUS: 0 
 multi_person: True
 kernel_sizes: [5]
 use_coordmaps: True
 fine_tune: True
 eval: False
 webcam: False
 video_or_frame: False

 baseline: 'hrnetv5'
 input_size: 512
 centermap_size: 64
 model_precision: 'fp32'
 val_batch_size: 1
 nw: 4
 gmodel_path: '../trained_models/CenterHMR.pkl' #'../trained_models/CenterHMR+CAR.pkl'
 save_visualization_on_img: True

 # default: run on demo/images and the results would be saved at demo/images_results
 # for video /path/to/project/CenterHMR_demo/videos/Messi_1
 demo_image_folder: '/path/to/image_folder' #'../demo/videos/Messi_1'
 output_dir: '/path/to/outputdir'
 save_mesh: False
 save_centermap: False
 save_dict_results: False
 multiprocess: False
